alias postgres='/Applications/Postgres.app/Contents/Versions/9.4/bin/psql -p5432'
alias start-wos-web='cd ~/dev/wos-storefront-web/ && DEBUG=myapp ./bin/www'
alias ngrok-wos-manager='ngrok -subdomain=wonderofsound -authtoken lK8vnL-P-aV_z1jgKNLY 3000'
alias jsdoc='yuidoc . --server 4000'
alias ls='ls -1'
alias byword='cd ~/Dropbox/Apps/Byword/'
alias diff='diff -y'
alias jcurl='curl -X POST -d @- $1 --header "Content-Type:application/json"'
alias weed='cd ~/dev/weedfs && ./weed'
